resolver: lts-9.1

packages:
- '.'
- location:
    git: https://github.com/serokell/msgpack-haskell.git
    commit: d0dc2d7bdeef569d1fe6cf876d04046e0845e796
  extra-dep: true
  subdirs:
    - msgpack
    - msgpack-rpc
- location:
    git: https://github.com/serokell/time-warp.git
    commit: b3ab04c1f42d6069caf9a6776e4e2c1ae666c065
  extra-dep: true

extra-deps:
- acid-state-0.14.3
- fmt-0.5.0.0
- serokell-util-0.5.0
- time-units-1.0.0
- universum-0.7.1

flags: {}

extra-package-dbs: []
