resolver: lts-9.1

packages:
- '.'
- location:
    git: https://github.com/serokell/msgpack-haskell.git
    commit: d0dc2d7bdeef569d1fe6cf876d04046e0845e796
  extra-dep: true
  subdirs:
    - msgpack
    - msgpack-rpc
- location:
    git: https://github.com/serokell/time-warp.git
    commit: f1b4934381462fb7edfc33c569878535f654093d
  extra-dep: true

extra-deps:
- acid-state-0.14.3
- fmt-0.5.0.0
- serokell-util-0.5.0
- time-units-1.0.0
- universum-0.7.1
- streaming-commons-0.1.16  # 0.1.17 is picked by default and it's broken :(
- monad-stm-0.1.0.2

flags: {}

extra-package-dbs: []
